var questions = [{
    "question":"p1.png",
    "option1": "11",
    "option2": "12",
    "option3": "14",
    "option4": "Nothing",
    "answer": "2" },{
    "question": "p2.png",
    "option1": "3",
    "option2": "8",
    "option3": "9",
    "option4": "Nothing",
    "answer": "1" },{
    "question": "p3.png",
    "option1": "70",
    "option2": "22",
    "option3": "29",
    "option4": "Nothing",
    "answer": "3"},{
    "question": "p4.png",
    "option1": "2",
    "option2": "3",
    "option3": "5",
    "option4": "Nothing",
    "answer": "3" },{
    "question": "p5.png",
    "option1": "5",
    "option2": "3",
    "option3": "2",
    "option4": "Nothing",
    "answer": "2" },{
    "question": "p6.png",
    "option1": "16",
    "option2": "17",
    "option3": "15",
    "option4": "Nothing",
    "answer": "3" },{
    "question": "p7.png",
    "option1": "14",
    "option2": "74",
    "option3": "78",
    "option4": "Nothing",
    "answer": "2" },{
    "question": "p8.png",
    "option1": "5",
    "option2": "6",
    "option3": "4",
    "option4": "Nothing",
    "answer": "2" },{
    "question": "p9.png",
    "option1": "85",
    "option2": "40",
    "option3": "45", 
    "option4": "Nothing",
    "answer": "3" },{
    "question": "p10.png",
    "option1": "5",
    "option2": "6",
    "option3": "8",
    "option4": "Nothing",
    "answer": "1" },{
    "question": "p11.png",
    "option1": "1",
    "option2": "7",
    "option3": "3",
    "option4": "Nothing",
    "answer": "2" },{
    "question": "p12.png",
    "option1": "66",
    "option2": "16",
    "option3": "18",
    "option4": "Nothing",
    "answer": "2" },{
    "question": "p13.png",
    "option1": "76",
    "option2": "78",
    "option3": "73",
    "option4": "Nothing",
    "answer": "3" },{
    "question": "p14.png",
    "option1": "5",
    "option2": "8",
    "option3": "6",
    "option4": "Nothing",
    "answer": "4" },{
    "question": "p15.png",
    "option1": "6",
    "option2": "9",
    "option3": "2",
    "option4": "Nothing",
    "answer": "4" },{
    "question": "p16.png",
    "option1": "26",
    "option2": "6",
    "option3": "2",
    "option4": "Nothing",
    "answer": "1" },{
    "question": "p17.png",
    "option1": "2",
    "option2": "4",
    "option3": "42",
    "option4": "Nothing",
    "answer": "3" }
    ];